package com.mycompany.dreamhouse.controller;
import com.mycompany.dreamhouse.dao.UserDao; import com.mycompany.dreamhouse.model.User; import com.mycompany.dreamhouse.util.PasswordUtil;
import jakarta.servlet.*; import jakarta.servlet.annotation.WebServlet; import jakarta.servlet.http.*; import java.io.*; import java.net.URLEncoder; import java.nio.charset.StandardCharsets; import java.sql.SQLException; import java.util.Locale;
@WebServlet("/auth/*")
public class AuthServlet extends HttpServlet {
 private final UserDao users=new UserDao();
 @Override protected void doGet(HttpServletRequest req,HttpServletResponse res)throws IOException{if("/status".equals(req.getPathInfo())){HttpSession s=req.getSession(false);boolean ok=s!=null&&s.getAttribute("userId")!=null;String role=ok?attribute(s,"role"):"";String name=ok?attribute(s,"name"):"";String email=ok?attribute(s,"email"):"";res.setContentType("application/json;charset=UTF-8");res.getWriter().write("{\"authenticated\":"+ok+",\"role\":\""+json(role)+"\",\"name\":\""+json(name)+"\",\"email\":\""+json(email)+"\"}");return;}res.sendError(405);}
 @Override protected void doPost(HttpServletRequest req,HttpServletResponse res)throws IOException{req.setCharacterEncoding("UTF-8");String path=req.getPathInfo();if("/register".equals(path))register(req,res);else if("/login".equals(path))login(req,res);else if("/logout".equals(path))logout(req,res);else res.sendError(404);}
 private void register(HttpServletRequest q,HttpServletResponse r)throws IOException{String name=trim(q.getParameter("name")),email=trim(q.getParameter("email")).toLowerCase(Locale.ROOT),password=q.getParameter("password"),confirm=q.getParameter("confirmPassword");if(name.length()<2||name.length()>100||!email.matches("^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$")){error(q,r,"register.html","details");return;}if(password==null||password.length()<8||password.length()>200||!password.equals(confirm)){error(q,r,"register.html","password");return;}try{if(users.findByEmail(email)!=null){error(q,r,"register.html","exists");return;}users.createUser(name,email,PasswordUtil.hash(password));r.sendRedirect(q.getContextPath()+"/login.html?registered=1");}catch(SQLException e){getServletContext().log("DreamHouse registration failed",e);error(q,r,"register.html",databaseErrorCode(e));}}
 private void login(HttpServletRequest q,HttpServletResponse r)throws IOException{String email=trim(q.getParameter("email")).toLowerCase(Locale.ROOT),password=q.getParameter("password"),role=trim(q.getParameter("role")).toUpperCase(Locale.ROOT);if(!role.equals("ADMIN")&&!role.equals("USER"))role="USER";try{User u=users.findByEmail(email);if(u==null||password==null||!PasswordUtil.verify(password,u.passwordHash())||!role.equals(u.role())){error(q,r,"login.html","invalid");return;}HttpSession old=q.getSession(false);if(old!=null)old.invalidate();HttpSession s=q.getSession(true);s.setMaxInactiveInterval(1800);s.setAttribute("userId",u.id());s.setAttribute("name",u.name());s.setAttribute("email",u.email());s.setAttribute("role",u.role());String page="ADMIN".equals(u.role())?"admin-dashboard.html":"index.html";String destination=q.getContextPath()+"/"+page;if("USER".equals(u.role()))destination+="?welcome="+URLEncoder.encode(u.name(),StandardCharsets.UTF_8);r.sendRedirect(destination);}catch(SQLException e){getServletContext().log("DreamHouse login failed",e);error(q,r,"login.html",databaseErrorCode(e));}}
 private void logout(HttpServletRequest q,HttpServletResponse r)throws IOException{HttpSession s=q.getSession(false);if(s!=null)s.invalidate();r.sendRedirect(q.getContextPath()+"/login.html?loggedOut=1");}
 private static String trim(String s){return s==null?"":s.trim();}
 private static String attribute(HttpSession session,String key){Object value=session.getAttribute(key);return value instanceof String?(String)value:"";}
 private static String json(String s){return s.replace("\\","\\\\").replace("\"","\\\"").replace("\n","\\n").replace("\r","\\r");}
 private static String databaseErrorCode(SQLException exception){for(Throwable cause=exception;cause!=null;cause=cause.getCause()){String message=cause.getMessage();if(message!=null&&(message.contains("No suitable driver")||message.contains("Connector/J is missing")))return "driver";if(message!=null&&message.contains("Public Key Retrieval is not allowed"))return "mysql-auth";}return "database";}
 private static void error(HttpServletRequest q,HttpServletResponse r,String page,String code)throws IOException{r.sendRedirect(q.getContextPath()+"/"+page+"?error="+code);}
}

